name: cast
description: Dart package to discover and connect with Chromecast devices
version: 2.1.0
homepage: https://github.com/johnvuko/flutter_cast

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bonsoir: '>=3.0.0'
  flutter:
    sdk: flutter
  protobuf: ^4.1.0

dev_dependencies:
  pedantic: ^1.11.1
  protoc_plugin: ^22.5.0
